version: "3.9"
services:
  redis:
    image: redis:latest
    volumes:
      - /tmp/redis:/data
    command: redis-server --save 60 1 --loglevel warning
  ping:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - redis
    ports:
      - 4567:4567
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/root/app
