version: "3.9"
services:
  redis:
    image: redis:latest
  ping:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 4567:4567
    environment:
      APP_ENV: production
      REDIS_URL: redis://redis:6379/0
